### ISSUE TITLE
Some issues in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [lisbono2001/ku-polls#1]
> 8.&nbsp;No limits on the number of survey items and number of responses.

As Mr James has posted in the classroom this morning, use "poll" instead of "survey" for now.

> 5.&nbsp;Application should be user-friendly that make users easy to use it.

The requirements, per instructions, should be testable. How can this be tested, given its subjective nature? *Usability* is a *non-functional requirement* that is not needed here for now.

Reading through this, some questions like, "Can anyone see the poll before it is open?" still remains. Addressing that would make the requirements more complete.

**Comment by lisbono2001** [comment]
- Change words ( survey --> poll ).
- Rewrite 5th requirement ( Remove non-functional requirement and add a more useful one ).

**Comment by MaiNorapong** [comment]
FYI non-functional requirements aren't bad; they are just another kind of requirements, one that isn't needed right now. One way of categorising requirements is to group them into *functional requirements* & *non-functional requirements*. You can learn more about it searching on Google. I've given you the keywords.

**Comment by lisbono2001** [comment]
Split requirements to functional and non-functional requirements
